### ISSUE TITLE
Improove face comparing (getting distance) quality

### ISSUE THREAD

**Issue by somuthink** [mobilesec/arcface-tensorflowlite#9]
I **love** this implementation of `ArcFace` at all, but facial `embedding` comparison (distance) **leaves much to be desired**, is there any ways or tips and tricks how to find distances in a **better way**? sorry if its a silly question

**Comment by p-hofer** [comment]
Thanks for the positive feedback.

Typically, the L2 norm is used as distance metric between two face recognition embeddings; that's why we use it in this repository.

You could also use different distance metrics (e.g. absolute distance and arc cosine similarity). While there may be slight variations in performance when using different distance metrics, we do not expect significant differences in results.

I don't think I understand what you mean with finding distances in a better way. Face recognition extracts an embedding from pre-processed faces. These numeric vectors are then used for comparisons.

If there's anything else left desired, feel free to contact me again.
